
package projetoinsight;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author otavio
 */
public class Tabelas extends javax.swing.JFrame {

    String EntradaHorarioDeTrabalho;
    String SaidaHorarioDeTrabalho;
    String EntradaMarcacoesFeitas;
    String SaidaMarcacoesFeitas;

    public Tabelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnSalvarHorarioDeTrabalho = new javax.swing.JButton();
        jbtnRemoverHorarioDeTrabalho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHorarioDeTrabalho = new javax.swing.JTable();
        jftSaidaHorarioDeTrabalho = new javax.swing.JFormattedTextField();
        jftEntradaHorarioDeTrabalho = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnSalvarMarcacoesFeitas = new javax.swing.JButton();
        jbtnRemoverMarcacoesFeitas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMarcacoesFeitas = new javax.swing.JTable();
        jftSaidaMarcacoesFeitas = new javax.swing.JFormattedTextField();
        jftEntradaMarcacoesFeitas = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAtraso = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableHoraExtra = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jbtnContabilizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtnSalvarHorarioDeTrabalho.setBackground(new java.awt.Color(51, 255, 51));
        jbtnSalvarHorarioDeTrabalho.setText("Salvar");
        jbtnSalvarHorarioDeTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarHorarioDeTrabalhoActionPerformed(evt);
            }
        });

        jbtnRemoverHorarioDeTrabalho.setBackground(new java.awt.Color(255, 102, 102));
        jbtnRemoverHorarioDeTrabalho.setText("Remover");
        jbtnRemoverHorarioDeTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverHorarioDeTrabalhoActionPerformed(evt);
            }
        });

        jLabel1.setText("Entrada:");

        jLabel2.setText("Saida:");

        jTableHorarioDeTrabalho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entrada", "Saida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableHorarioDeTrabalho);

        try {
            jftSaidaHorarioDeTrabalho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftSaidaHorarioDeTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftSaidaHorarioDeTrabalhoActionPerformed(evt);
            }
        });

        try {
            jftEntradaHorarioDeTrabalho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftEntradaHorarioDeTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftEntradaHorarioDeTrabalhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jftEntradaHorarioDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jftSaidaHorarioDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(122, 122, 122))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jbtnSalvarHorarioDeTrabalho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnRemoverHorarioDeTrabalho)
                        .addGap(21, 21, 21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jftSaidaHorarioDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftEntradaHorarioDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRemoverHorarioDeTrabalho)
                    .addComponent(jbtnSalvarHorarioDeTrabalho))
                .addContainerGap())
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Horario De Trabalho");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtnSalvarMarcacoesFeitas.setBackground(new java.awt.Color(51, 255, 51));
        jbtnSalvarMarcacoesFeitas.setText("Salvar");
        jbtnSalvarMarcacoesFeitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarMarcacoesFeitasActionPerformed(evt);
            }
        });

        jbtnRemoverMarcacoesFeitas.setBackground(new java.awt.Color(255, 102, 102));
        jbtnRemoverMarcacoesFeitas.setText("Remover");
        jbtnRemoverMarcacoesFeitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverMarcacoesFeitasActionPerformed(evt);
            }
        });

        jLabel4.setText("Entrada:");

        jLabel7.setText("Saida:");

        jTableMarcacoesFeitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entrada", "Saida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableMarcacoesFeitas);

        try {
            jftSaidaMarcacoesFeitas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftEntradaMarcacoesFeitas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftEntradaMarcacoesFeitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftEntradaMarcacoesFeitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jftEntradaMarcacoesFeitas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jftSaidaMarcacoesFeitas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(122, 122, 122))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jbtnSalvarMarcacoesFeitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnRemoverMarcacoesFeitas)
                        .addGap(21, 21, 21)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jftSaidaMarcacoesFeitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftEntradaMarcacoesFeitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRemoverMarcacoesFeitas)
                    .addComponent(jbtnSalvarMarcacoesFeitas))
                .addContainerGap())
        );

        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Marcações Feitas");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableAtraso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entrada", "Saida"
            }
        ));
        jScrollPane2.setViewportView(jTableAtraso);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Atraso");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableHoraExtra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entrada", "Saida"
            }
        ));
        jScrollPane4.setViewportView(jTableHoraExtra);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("Hora Extra");

        jbtnContabilizar.setBackground(new java.awt.Color(255, 153, 0));
        jbtnContabilizar.setText("Contabilizar");
        jbtnContabilizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnContabilizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(0, 793, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(jbtnContabilizar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnContabilizar)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalvarHorarioDeTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarHorarioDeTrabalhoActionPerformed
        
        DefaultTableModel modeloPadrao = (DefaultTableModel) this.jTableHorarioDeTrabalho.getModel();
 
        modeloPadrao.addRow(new Object[]{
            this.EntradaHorarioDeTrabalho = jftEntradaHorarioDeTrabalho.getText(), 
            this.SaidaHorarioDeTrabalho = jftSaidaHorarioDeTrabalho.getText()
            
               
        });
            int rowCount = modeloPadrao.getRowCount();
            System.out.println("Contador linha Horario Trabalho: " +rowCount);
            
            Object valEntrada1 = modeloPadrao.getValueAt(rowCount-1, 0);
            System.out.println(valEntrada1.toString());
            
            Object valEntrada2 = modeloPadrao.getValueAt(rowCount-1, 1);
            System.out.println(valEntrada2.toString());
            
            
            
     
            
    }//GEN-LAST:event_jbtnSalvarHorarioDeTrabalhoActionPerformed

    private void jbtnRemoverHorarioDeTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverHorarioDeTrabalhoActionPerformed
        DefaultTableModel modeloPadrao = (DefaultTableModel) this.jTableHorarioDeTrabalho.getModel();
        
        int linha = this.jTableHorarioDeTrabalho.getSelectedRow();
        
        modeloPadrao.removeRow(linha);
    }//GEN-LAST:event_jbtnRemoverHorarioDeTrabalhoActionPerformed

    private void jftEntradaHorarioDeTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftEntradaHorarioDeTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftEntradaHorarioDeTrabalhoActionPerformed

    private void jbtnSalvarMarcacoesFeitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarMarcacoesFeitasActionPerformed
       DefaultTableModel tableMarcacoesFeitas = (DefaultTableModel) this.jTableMarcacoesFeitas.getModel();
       
       tableMarcacoesFeitas.addRow(new Object[]{
            this.EntradaMarcacoesFeitas = jftEntradaMarcacoesFeitas.getText(), 
            this.SaidaMarcacoesFeitas = jftSaidaMarcacoesFeitas.getText()  
        });
        //contador de linhas 
        int rowCount = tableMarcacoesFeitas.getRowCount();
        System.out.println("Contador linha Marcações Feitas: " +rowCount);
        
        //referencia dos valores da coluna
        Object valEntrada3 = tableMarcacoesFeitas.getValueAt(rowCount-1, 0);
        System.out.println(valEntrada3.toString());
            
        Object valEntrada4 = tableMarcacoesFeitas.getValueAt(rowCount-1, 1);
        System.out.println(valEntrada4.toString());
       
    }//GEN-LAST:event_jbtnSalvarMarcacoesFeitasActionPerformed
        //Função para remover selecionando a linha na tabela
    private void jbtnRemoverMarcacoesFeitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverMarcacoesFeitasActionPerformed
        DefaultTableModel modeloPadrao = (DefaultTableModel) this.jTableMarcacoesFeitas.getModel();
        
        int linha = this.jTableMarcacoesFeitas.getSelectedRow();
        
        modeloPadrao.removeRow(linha);
    }//GEN-LAST:event_jbtnRemoverMarcacoesFeitasActionPerformed

    private void jftEntradaMarcacoesFeitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftEntradaMarcacoesFeitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftEntradaMarcacoesFeitasActionPerformed

    private void jftSaidaHorarioDeTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftSaidaHorarioDeTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftSaidaHorarioDeTrabalhoActionPerformed

    private void jbtnContabilizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnContabilizarActionPerformed
        //Variaveis para receber o valor de horario de entrada e saida das tabelas
        String horarioEntrada,horarioSaida;
        
        //Importando as tabelas criadas para função contabilizar
        DefaultTableModel tableHorarioTrabalho = (DefaultTableModel) this.jTableHorarioDeTrabalho.getModel();
        DefaultTableModel tableMarcacoesFeitas = (DefaultTableModel) this.jTableMarcacoesFeitas.getModel();
        
        //Contadores de linhas para array
        int rowCountHorarioTrabalho = tableHorarioTrabalho.getRowCount();
        int rowCountMarcacoesFeitas = tableMarcacoesFeitas.getRowCount();
        
        //Criação dos arrays das tabelas
        ArrayList<String> arrayHorarioTrabalho = new ArrayList<>();
        ArrayList<String> arrayMarcacoesFeitas = new ArrayList<>();
        
        //For para contabilizar os arrays
        for(int i = 0; i < rowCountHorarioTrabalho; i++){
            horarioEntrada = tableHorarioTrabalho.getValueAt(i, 0).toString();
            horarioSaida = tableHorarioTrabalho.getValueAt(i, 1).toString();   
            arrayHorarioTrabalho.add(horarioEntrada);
            arrayHorarioTrabalho.add(horarioSaida);
        }
        
        for(int i = 0; i < rowCountMarcacoesFeitas; i++){
            horarioEntrada = tableMarcacoesFeitas.getValueAt(i, 0).toString();
            horarioSaida = tableMarcacoesFeitas.getValueAt(i, 1).toString();   
            arrayMarcacoesFeitas.add(horarioEntrada);
            arrayMarcacoesFeitas.add(horarioSaida);
        }
         System.out.println(arrayHorarioTrabalho.toString());
         System.out.println(arrayMarcacoesFeitas.toString());
       
        
        for (int i = 0; i < arrayHorarioTrabalho.size(); i++) {
            //convertendo String para date
            SimpleDateFormat sdfConvert = new SimpleDateFormat("HH:mm");
            try{
            Date horarioTrabalho = sdfConvert.parse(arrayHorarioTrabalho.get(i));
            Date horarioMarcacao = sdfConvert.parse(arrayMarcacoesFeitas.get(i));
            
            System.out.println(horarioTrabalho);
            System.out.println(horarioMarcacao);
            
            if(i % 2 == 0){
              switch(horarioTrabalho.compareTo(horarioMarcacao)){
                  case -1:
                      System.out.println("menor");
                      tableHorarioTrabalho.getValueAt(1, 1);
                      //jTableAtraso.setValueAt(horarioTrabalho, 1, 1);
                     
                  break;
                  case 0:
                      System.out.println("igual");
                  break;
                  case 1:
                      System.out.println("maior");
                  break;
              }   
            }else{
                
            }
            
            }catch(ParseException ex){
                System.out.println("Erro :"+ ex);
            }
       
            
          //System.out.println(arrayHorarioTrabalho.get(i));
          //comparação de par
          //horario de entrada
          

          //horario de saida
        }
         
    }//GEN-LAST:event_jbtnContabilizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableAtraso;
    private javax.swing.JTable jTableHoraExtra;
    private javax.swing.JTable jTableHorarioDeTrabalho;
    private javax.swing.JTable jTableMarcacoesFeitas;
    private javax.swing.JButton jbtnContabilizar;
    private javax.swing.JButton jbtnRemoverHorarioDeTrabalho;
    private javax.swing.JButton jbtnRemoverMarcacoesFeitas;
    private javax.swing.JButton jbtnSalvarHorarioDeTrabalho;
    private javax.swing.JButton jbtnSalvarMarcacoesFeitas;
    private javax.swing.JFormattedTextField jftEntradaHorarioDeTrabalho;
    private javax.swing.JFormattedTextField jftEntradaMarcacoesFeitas;
    private javax.swing.JFormattedTextField jftSaidaHorarioDeTrabalho;
    private javax.swing.JFormattedTextField jftSaidaMarcacoesFeitas;
    // End of variables declaration//GEN-END:variables
}
